FROM python:3.9

COPY . /app	
WORKDIR /app

ENV ENDPOINT_URL="http://host.docker.internal:4566/"
ENV AWS_ACCESS_KEY_ID='test'
ENV AWS_SECRET_ACCESS_KEY="test"
ENV AWS_DEFAULT_REGION="us-east-1"
ENV AWS_REGION="us-east-1"
ENV PROFILE_NAME="localstack"

RUN python3 -m pip install -r requirements.txt

EXPOSE 5000

RUN chmod +x gunicorn_starter.sh

ENTRYPOINT ["./gunicorn_starter.sh"]
